name: Build FFmpeg for Audio-Only

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config libasound2-dev libvorbis-dev libopus-dev libmp3lame-dev libflac-dev libsoxr-dev

      - name: Download FFmpeg source code
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-6.0.0.tar.gz
          tar -xzvf ffmpeg-6.0.0.tar.gz
          cd ffmpeg-6.0.0

      - name: Configure FFmpeg for Audio-Only
        run: |
          ./configure \
            --disable-everything \
            --enable-demuxer=wav,aac,flac,ogg \
            --enable-decoder=aac,flac,opus,vorbis,mp3 \
            --enable-parser=aac,flac,opus,vorbis,mp3 \
            --enable-filter=anull \
            --enable-encoder=aac,flac,opus,vorbis,mp3 \
            --enable-muxer=wav,flac,ogg \
            --enable-protocol=file

      - name: Build FFmpeg
        run: make -j$(nproc)

      - name: Install FFmpeg
        run: sudo make install

      - name: Verify FFmpeg
        run: ffmpeg -version

      - name: Run tests
        run: |
          cd ./${{ github.workspace }}/test_build.sh
